import sys
import numpy as np
import librosa
import matplotlib.pyplot as plt
import argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Plot repeat-padding vs zero-padding example.")
    parser.add_argument("npz", type=str, help="Path to npz file to get audio from")
    args = parser.parse_args()

    r = np.load(args.npz, allow_pickle=False)
    if "source_files" not in r:
        print("Error: 'source_files' not found in npz. Ensure it was generated by the pipeline.")
        sys.exit(1)
        
    audio_path = str(r["source_files"][0])
    print(f"Loading audio from: {audio_path}")
    
    # Load a 2-second snippet from 10s to 12s, at 32kHz because perch
    sr = 32000
    try:
        y, _ = librosa.load(audio_path, sr=sr, offset=10.0, duration=2.0)
    except Exception as e:
        print(f"Error loading audio: {e}")
        sys.exit(1)

    target_len = sr * 5  
    current_len = len(y)
    
    # Repeat padding
    reps = int(np.ceil(target_len / current_len))
    y_repeat = np.tile(y, reps)[:target_len]
    
    # Zero padding
    pad_len = target_len - current_len
    y_zero = np.pad(y, (0, pad_len), mode="constant", constant_values=0.0)
    
    # Spectrogram conversion from browse_timeline
    from scipy.signal import spectrogram as scipy_spectrogram
    
    def get_spec(audio):
        nperseg = min(512, len(audio))
        freqs, times, Sxx = scipy_spectrogram(audio, fs=sr, nperseg=nperseg, noverlap=nperseg * 3 // 4)
        Sxx_db = 10 * np.log10(Sxx + 1e-10)
        return freqs, times, Sxx_db

    freqs, times_orig, Sxx_orig = get_spec(y)
    _, times_zero, Sxx_zero = get_spec(y_zero)
    _, times_repeat, Sxx_repeat = get_spec(y_repeat)
    
    vmin = Sxx_orig.min()
    vmax = Sxx_orig.max()
    
    def plot_spec(ax, times, Sxx_db, title):
        ax.pcolormesh(times, freqs, Sxx_db, shading="auto", cmap="Blues_r", rasterized=True, vmin=vmin, vmax=vmax)
        ax.set_title(title, fontsize=14)
        ax.set_ylabel("Freq (Hz)", fontsize=12)
        ax.set_ylim(0, sr // 2)

    # Plotting
    fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
    
    plot_spec(axes[0], times_orig, Sxx_orig, "Original Audio Window (2.0s)")
    plot_spec(axes[1], times_zero, Sxx_zero, "Zero-Padded (to 5.0s)")
    plot_spec(axes[2], times_repeat, Sxx_repeat, "Repeat-Padded (to 5.0s)")
    
    axes[2].set_xlabel("Time (s)", fontsize=14)
    
    for ax in axes:
        ax.set_xlim(0, 5.0)
        ax.tick_params(labelsize=12)
        
    plt.tight_layout()
    out_path = Path(args.npz).parent / "padding_example.png"
    plt.savefig(out_path, dpi=150)
    print(f"Saved plot to {out_path}")

if __name__ == "__main__":
    main()
